<<<<<<< copilot/fix-73dd5534-d51c-417c-9cc7-aa42f42aa60c
# Configuration for bioarchitettura.org
site_title: "Fondazione Italiana per la Bioarchitettura"
site_description: "L'Ente italiano di riferimento nell'ambito del costruire sano ed ecologico"
site_url: "https://bioarchitettura.github.io/web"
language: "it"

# Build settings
content_directory: "public"
theme: "minima"

# Site metadata
author: "Fondazione Italiana per la Bioarchitettura"
keywords: "bioarchitettura, architettura sostenibile, costruzione ecologica"

# Navigation
main_sections:
  - home
  - about
  - services
  - contact
=======
backend:
  name: github
  repo: bioarchitettura/web
  branch: main
  site_domain: bioarchitettura.github.io
  base_url: https://bioarchitettura.github.io

media_folder: "assets/images/uploads"
public_folder: "/web/assets/images/uploads"

locale: 'it'

collections:
  - name: "rivista"
    label: "Rivista"
    folder: "_rivista"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Corpo", name: "body", widget: "markdown" }
      - { label: "Immagine", name: "image", widget: "image", required: false }
  - name: "archivio"
    label: "Archivio"
    folder: "_archivio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Corpo", name: "body", widget: "markdown" }
      - { label: "Allegato", name: "attachment", widget: "file", required: false }
  - name: "blog"
    label: "Notizie"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Corpo", name: "body", widget: "markdown" }
      - { label: "Immagine", name: "image", widget: "image", required: false }
>>>>>>> main
