# Configuration for bioarchitettura.org
site_title: "Fondazione Italiana per la Bioarchitettura"
site_description: "L'Ente italiano di riferimento nell'ambito del costruire sano ed ecologico"
site_url: "https://bioarchitettura.github.io/web"
language: "it"

# Build settings
content_directory: "public"
theme: "minima"

# Site metadata
author: "Fondazione Italiana per la Bioarchitettura"
keywords: "bioarchitettura, architettura sostenibile, costruzione ecologica"

# Navigation
main_sections:
  - home
  - about
  - services
  - contact