# Netlify Configuration File
[build]
  # Directory to change to before starting a build
  base = "/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "_site"
  
  # A command to run before the main build command
  command = "jekyll build"

[build.environment]
  # Ruby version for Jekyll
  RUBY_VERSION = "3.1.1"
  # Ensure CMS is accessible
  NODE_VERSION = "18"

# Headers for security and CMS functionality
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Headers specifically for CMS admin
[[headers]]
  for = "/admin/*"
  [headers.values]
    # Allow CMS to function properly
    X-Frame-Options = "SAMEORIGIN"
    Cache-Control = "no-cache"

# Redirects for clean URLs and CMS access
[[redirects]]
  # Redirect root to main content
  from = "/"
  to = "/public/"
  status = 302
  conditions = {Role = ["admin"], Country = ["!*"]}

# Force HTTPS
[[redirects]]
  from = "http://bioarchitettura.netlify.app/*"
  to = "https://bioarchitettura.netlify.app/:splat"
  status = 301
  force = true

# Ensure CMS admin is accessible
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[context.production]
  command = "jekyll build --future"

[context.deploy-preview]
  command = "jekyll build --drafts --future"

[context.branch-deploy]
  command = "jekyll build --drafts --future"