[build]
  # Directory to publish from
  publish = "_site"
  
  # Build command
  command = "jekyll build"

[build.environment]
  # Set Ruby version
  RUBY_VERSION = "3.2.0"
  JEKYLL_ENV = "production"

# Handle redirects for admin panel SPA routing
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Optional: fallback for other routes (uncomment if needed)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200