name: Deploy Rivista to GitHub Pages

on:
  push:
    branches: ["rivista"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "gh-pages-rivista"
  cancel-in-progress: false

jobs:
  # Build job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rivista Branch
        uses: actions/checkout@v4
        with:
          ref: rivista

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Create Gemfile if missing
        run: |
          if [ ! -f Gemfile ]; then
            echo "Gemfile not found, creating basic Gemfile..."
            cat > Gemfile << 'EOF'
          source "https://rubygems.org"
          gem "jekyll", "~> 4.2.2"
          gem "minima", "~> 2.5"
          gem "jekyll-feed", "~> 0.12"
          gem "jekyll-sitemap", "~> 1.4"
          platforms :mingw, :x64_mingw, :mswin, :jruby do
            gem "tzinfo", "~> 1.2"
            gem "tzinfo-data"
          end
          gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
          gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
          EOF
            bundle install
          fi

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true