name: Jekyll site CI
- name: Check if blocked.jsonl or blocked.md exists
  id: check_files
  run: |
    if ls /home/runner/work/_temp/runtime-logs/blocked.* 1> /dev/null 2>&1; then
      echo "found=true" >> $GITHUB_OUTPUT
    else
      echo "found=false" >> $GITHUB_OUTPUT
    fi

- name: Upload blocked artifacts if present
  if: steps.check_files.outputs.found == 'true'
  uses: actions/upload-artifact@v4
  with:
    name: blocked
    path: /home/runner/work/_temp/runtime-logs/blocked.*
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Sets comprehensive permissions of the GITHUB_TOKEN for maximum compatibility  
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
